CREATE DATABASE BanGiay
GO
--
USE DATABASE BanGiay
GO

--TABLE--
CREATE TABLE Loai
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaLoai VARCHAR(10) UNIQUE NOT NULL,
	TenLoai NVARCHAR(20)
)

CREATE TABLE NhanVien
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaNhanVien VARCHAR(10) UNIQUE NOT NULL,
	TenNhanVien NVARCHAR(100),
	GioiTinh NVARCHAR(10),
	NgaySinh DATE,
	DiaChi NVARCHAR(200),
	DienThoai VARCHAR(20),
	CMND VARCHAR(20),
	MaLoai VARCHAR(10), --FK--
	Luong FLOAT,
	TinhTrang NVARCHAR(20)
)

CREATE TABLE TaiKhoan
(
	TaiKhoan VARCHAR(20) PRIMARY KEY,
	MatKhau VARCHAR(30) NOT NULL,
	Email VARCHAR(100),
	Ten NVARCHAR(100),
	DienThoai VARCHAR(20),
	CMND VARCHAR(20),
	MaLoai VARCHAR(10), --FK--
	NgayTao DATETIME,
	TinhTrang NVARCHAR(20)
)

CREATE TABLE SanPham
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaSanPham VARCHAR(10) UNIQUE NOT NULL,
	TenSanPham NVARCHAR(100),
	TaiKhoan VARCHAR(20) NOT NULL, --FK--
	Size INT,
	Mau NVARCHAR(20),
	Hang NVARCHAR(50),
	Gia FLOAT,
	SoLuong INT,
	Hinh NVARCHAR(200),
	ChiTiet NVARCHAR(500),
	MaKhuyenMai VARCHAR(10), --????--
	TinhTrang NVARCHAR(20)
)

CREATE TABLE PhieuNhap
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaPhieuNhap VARCHAR(10) UNIQUE NOT NULL,
	MaNhanVien VARCHAR(10) NOT NULL, --FK--
	TaiKhoan VARCHAR(20) NOT NULL, --FK--
	NgayNhap DATETIME,
	TongTien FLOAT,
	TinhTrang NVARCHAR(20)
)

CREATE TABLE ChiTietPhieuNhap
(
	MaPhieuNhap VARCHAR(10) NOT NULL, --PK, FK--
	MaSanPham VARCHAR(10) NOT NULL, --PK, FK--
	SoLuong INT,
	Gia FLOAT
)

CREATE TABLE PhieuGiao
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaPhieuGiao VARCHAR(10) UNIQUE NOT NULL,
	CMNDGiao VARCHAR(20) NOT NULL,
	TaiKhoan VARCHAR(20) NOT NULL, --FK--
	DiaChi NVARCHAR(200),
	NgayTao DATETIME,
	NgayGiao DATETIME,
	TongTien FLOAT,
	TinhTrang NVARCHAR(20)
)

CREATE TABLE ChiTietPhieuGiao
(
	MaPhieuGiao VARCHAR(10) NOT NULL, --PK, FK--
	MaSanPham VARCHAR(10) NOT NULL, --PK, FK--
	SoLuong INT,
	Gia FLOAT
)

CREATE TABLE PhieuDat
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaPhieuDat VARCHAR(10) UNIQUE NOT NULL,
	TaiKhoan VARCHAR(20) NOT NULL, --FK--
	NgayTao DATETIME,
	TinhTrang NVARCHAR(20)
)

CREATE TABLE ChiTietPhieuDat
(
	MaPhieuDat VARCHAR(10) NOT NULL, --PK, FK--
	MaSanPham VARCHAR(10) NOT NULL, --PK, FK--
	SoLuong INT
)

CREATE TABLE Quan --Quận--
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaQuan VARCHAR(10) UNIQUE NOT NULL,
	TenQuan NVARCHAR(20),
	Gia FLOAT
)

CREATE TABLE DiaChi
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	TaiKhoan VARCHAR(20) NOT NULL, --FK--
	Duong NVARCHAR(100) NOT NULL, --Đường--
	MaQuan VARCHAR(10) NOT NULL, --FK--
	Phuong NVARCHAR(20),
	TinhTrang NVARCHAR(20)
)

CREATE TABLE KhuyenMai
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaKhuyenMai VARCHAR(10) UNIQUE NOT NULL,
	NgayBatDau DATETIME,
	NgayKetThuc DATETIME,
	GiamGia FLOAT,
	NoiDung NVARCHAR(500),
	TinhTrang NVARCHAR(20)
)

CREATE TABLE HoaHong
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaHoaHong VARCHAR(10) UNIQUE NOT NULL,
	PhanTram FLOAT,
	NgayBatDau DATETIME
)

CREATE TABLE HopDong
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaHopDong VARCHAR(10) UNIQUE NOT NULL,
	MaNhanVien VARCHAR(10) NOT NULL, --FK--
	NgayBatDau DATETIME,
	NgayKetThuc DATETIME,
	Gia FLOAT
)

CREATE TABLE QuangCao
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaQuangCao VARCHAR(10) UNIQUE NOT NULL,
	MaGoiQuangCao VARCHAR(10) NOT NULL, --FK--
	Hinh NVARCHAR(200) NOT NULL,
	NgayBatDau DATETIME,
	NgayKetThuc DATETIME,
	ChuThich NVARCHAR(500),
	TinhTrang NVARCHAR(20)
)

CREATE TABLE GoiQuangCao
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MaGoiQuangCao VARCHAR(10) UNIQUE NOT NULL,
	ViTri NVARCHAR(100),
	Gia FLOAT,
	ThoiLuong INT --Ngày--
)

CREATE TABLE GioHang
(
	TaiKhoan VARCHAR(20) NOT NULL, --PK, FK--
	MaSanPham VARCHAR(10) NOT NULL, --PK, FK--
	TinhTrang NVARCHAR(20)
)